Repository pypa/setuptools, pull requests merged in 2021-11, with the labels that each got.

#2871 Document that pip works with editable `setup.cfg`
  changelog.d/2871.doc.rst
  docs/conf.py
  docs/userguide/quickstart.rst
Labels: enhancement, documentation

#2870 Fail on a multiline distribution package summary
  changelog.d/2870.breaking.rst
  setuptools/dist.py
Labels: enhancement, trivial, minor

#2869 [Docs] Replace PNG/ICO images with SVG
  changelog.d/2867.doc.1.rst
  changelog.d/2867.doc.2.rst
  docs/_ext/_custom_icons.py
  docs/conf.py
  docs/images/README.rst
  docs/images/banner-640x320.png
  docs/images/banner-negative-640x320.png
  docs/images/favicon.ico
  docs/images/favicon.svg
  docs/images/favicon.xcf
  docs/images/logo-demo-editable-inkscape.png
  docs/images/logo-demo.svg
  docs/images/logo-editable-inkscape.png
  docs/images/logo-inline-negative.png
  docs/images/logo-inline.png
  docs/images/logo-negative.png
  docs/images/logo-over-white.png
  docs/images/logo-symbol-only.png
  docs/images/logo-symbol-only.svg
  docs/images/logo-text-only.png
  docs/images/logo.png
Labels: enhancement, trivial, documentation
