Repository pypa/setuptools, pull requests merged in 2022-02, with the labels that each got.

#2923 Add integration testing with python from Debian, Ubuntu, Fedora, Gentoo, Arch Linux, OpenSUSE, Slackware
  .github/workflows/ci-sage.yml
Labels: proposal

#3099 Add timeout to `test_build_meta`
  setuptools/tests/test_build_meta.py
  tox.ini
Labels: auto-merge

#3133 Tests using virtual environments: pass the copy of existing env to the subprocesses
  changelog.d/3133.misc.rst
  setuptools/tests/environment.py
  setuptools/tests/fixtures.py
Labels: enhancement
